[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shark_dao = "3vHSdBG1jZxq8r39y1NH4Mts6LyccMPs6WX6u2ic2BE1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init.ts"
new_preorder = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/new_preorder.ts"
preorder = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/preorder.ts"
sol_preorder = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sol_preorder.ts"
lock_token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/lock_token.ts"
withdraw_sol = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw_sol.ts"
withdraw_usdt = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/withdraw_usdt.ts"
auth = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/auth.ts"
