[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
shark_dao = "AowwQVNHgEYR4Lbmy2QR1CE9PqCkmHiKWZDscnfPy1Ch"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init.ts"
new_preorder = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/new_preorder.ts"
preorder = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/preorder.ts"
lock_token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/lock_token.ts"
